### ISSUE TITLE
access private URLs on LXRotatingFileEndpoint

### ISSUE THREAD

**Issue by rabidaudio** [logkit/logkit#11]
If there a reason properties like `directoryURL` and `currentURL` are `private` on `LXRotatingFileEndpoint`? It would be really useful to have read-only access to URLs for manipulating log files (e.g. uploading them to a server, deleting old logs, etc). 

At the moment, I have to use

``` swift
let directory = NSFileManager.defaultManager().URLsForDirectory(.ApplicationSupportDirectory, inDomains: .UserDomainMask).first!.URLByAppendingPathComponent(NSBundle.mainBundle().bundleIdentifier!, isDirectory: true).URLByAppendingPathComponent("logs", isDirectory: true)
```

which is terribly verbose and seems really fragile (if say LogKit changes the default file directory in a future version).

**Comment by justinpawela** [comment]
Hi @rabidaudio. I don't think there is a concrete reason those properties are private, other than a personal preference to minimize public API that has no public purpose. Certainly you are presenting a use case that I had not anticipated but seems worthwhile.

My initial impression is that those two properties in particular could be made public without too much concern, considering that they are currently read-only, and I can't think of a reason why we would want to remove public read-only access in the future. Obviously, keeping the URLs private does little to stop a hapless dev from messing with the files while they are currently in-use, potentially messing up the logger.

---

Just to play devil's advocate, I would point out that your workaround is not the only way to achieve those goals. A developer could:
1. provide their own `baseURL`, allowing them to be free from the dependency on LogKit's default URLs, or
2. use the built-in `LXHTTPEndpoint` to upload log entries without having to manually access the files, or
3. build their own Endpoint, allowing them to do basically whatever they wanted.

However, I still see little reason for restricting access to the URLs.

---

Do you have any thoughts regarding whether any of the couter-arguments presented above make sense? And do you think the two properties `directoryURL` and `currentURL` would be sufficient for your intended purposes?

BTW, +1 for deleting old log files (particularly with `LXDatedFileEndpoint`). I've opened issue #12, as that's something a dev shouldn't have to do manually.

**Comment by rabidaudio** [comment]
I would love to use an HTTP endpoint in the future, but that would require an API change that I can't do at the moment. The current API is file based rather than entry based. I'm providing my own `baseURL` at the moment, but that still means I have to use the nasty code above to make the `baseURL`.

My current relatively dirty solution until I can make an API change is to use an `LXDatedFileEndpoint` and then at app start submit and delete any log files from previous days. If you can think of a better way, I'm open to suggestions. (Maybe a custom `LXRotatingFileEndpoint` that uploads and rotates on app exit?)

In this particular use case, `directoryURL` might be enough, but both would be ideal. I can imagine there are other use cases outside of this one where `currentURL` would be valuable.

**Comment by justinpawela** [comment]
@rabidaudio Could you check out PR #13 and see if you think it addresses your issues?

I made the two properties in question public, along with adding a pair of `NSNotification`s for before & after log file rotation.

Thanks.

**Comment by rabidaudio** [comment]
Looks good. The `NSNotification` bit is perfect actually. I might switch to using a regular `LXRotatingFileEndpoint` and set the file size relatively small, and then submit and delete after rotation.

Thanks for the crazy fast response on this!
