### ISSUE TITLE
LogKit causing Apple to detect IDFA call

### ISSUE THREAD

**Issue by rabidaudio** [logkit/logkit#16]
When I submitted to the App Store, Apple detected [IDFA tracking code usage](https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/SubmittingTheApp.html#//apple_ref/doc/uid/TP40011225-CH33-SW8) in our app and asked us to explain it's usage. It turns out the [`advertisingID` line in `LogKit.swift`](/logkit/logkit/blob/5cd2a8e54fe831102c9fc932089a54042cf826f2/Source/LogKit.swift#L136) was the culprit. I removed the call in my branch and Apple let us submit without complaining.

It seems that even though LogKit is not accessing `advertisingIdentifier` unless `adManager.advertisingTrackingEnabled` is true, Apple detects the existence of the line in the source code anyway. Not sure how to fix this, as I doubt the state of `advertisingTrackingEnabled` is known at compile time.

**Comment by justinpawela** [comment]
Thank you for reporting this!  I agree that this will need to come out for situations like yours, where you are not using the AdvertisingID.

I am exploring options for workarounds so as not to lose the ID entirely for a developer that is using it.  Open to suggestions!

**Comment by rabidaudio** [comment]
They only solution I can think of is a compile flag, e.g. `-DLKADTRACKINGENABLED` and then

``` swift
#ifdef LKADTRACKINGENABLED
    let adManager = ASIdentifierManager.sharedManager()
    let advertisingID = adManager.advertisingTrackingEnabled ? adManager.advertisingIdentifier.UUIDString : ""
#else
    let advertisingID = ""
#end
```

Vice versa is also possible (defaults to on and compiler flag turns it off). I'd be happy to send a PR.

**Comment by justinpawela** [comment]
That seems very reasonable, thanks.

I'd love a PR if you don't mind & have time.
