### ISSUE TITLE
Carthage prevents eliminating IDFA review

### ISSUE THREAD

**Issue by justinpawela** [logkit/logkit#19]
Carthage provides no method for defining custom Swift compiler flags in dependencies, and ignores the dependency's settings. Thus, the method of disabling `deviceAdvertisingID` by default -- by using a "disabled" flag included by default -- is not possible.

The best solution at this time appears to be to reversing the compiler flag -- make it an "enabled" flag that is absent by default.  This will keep the `deviceAdvertisingID` disabled by default, and allow interested developers to add the "enable" flag to enable.

Unfortunately, this means there will be no way to enable the ID when LogKit is installed using Carthage.

**Comment by mark-anders** [comment]
Are you going to put in a request to Carthage?

**Comment by justinpawela** [comment]
**I was wrong about Carthage not honoring a dependency's build settings.**

Carthage does use the build settings as provided by the project you added to the Cartfile. In fact, if you modify a dependency in its `Carthage/Checkout` folder, next time Carthage builds it will use those modifications. Thus, one could add/remove the compiler flag within the checked-out LogKit project and then rebuild.

The limitation here is that Carthage advises you do not do this, as a future `carthage checkout` (or `update`) could clobber your modifications. However, they provide a `--use-submodules` option for their `checkout` or `update` commands. If you use that option, you get a real living Git submodule that you can modify safely. It's a little more work for the developer with the submodule, however, as I think Carthage is pretty hands-off about it after that. So (for example) upgrading to a new LogKit version might require the dev to do a manual Git checkout of a new tag. Not as automated anymore, but then again, I guess the point of Carthage is that it's supposed to be minimal!

**Comment by justinpawela** [comment]
Actually, having spent even more time thinking about this, I think the solution is even simpler.

Fork LogKit, update the compiler flag as desired, commit, and point your Cartfile at your fork.

You just have to remember to [fetch & merge](https://help.github.com/articles/syncing-a-fork/) upstream LogKit changes into your fork before Carthage can install any updates.

If you do use Carthage on a regular basis, please let me know if I'm on the right track here.

**Comment by mark-anders** [comment]
I do use Carthage and really liked it.  It's quite refreshing after dealing with CocoaPods, so I think it's very important to support.

I am NOT familiar with the `deviceAdvertisingID` issue, but I think what you're proposing is to not include it so that those who are not dealing with it don't have to do anything special. Those that do need it would fork and add the flag to their version of the library.

That seems like a good approach to me.

**Comment by justinpawela** [comment]
I agree that Carthage seems easier to stomach than CocoaPods! You are also correct regarding the intentions with the Advertising ID.

Thanks for your input!
