### ISSUE TITLE
Building for Carthage fails

### ISSUE THREAD

**Issue by mark-anders** [logkit/logkit#20]
I just tried integrating 2.3.0 and got a failure when building with Carthage:

```
The following build commands failed:
    CompileSwift normal arm64 /Users/anders/Documents/dev/App/contextul-ios/Carthage/Checkouts/logkit/Tests/LogKitTests.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/anders/Documents/dev/App/contextul-ios/Carthage/Checkouts/logkit/Tests/LogKitTests.swift:20:18: error: module 'LogKit' was not compiled for testing
A shell task failed with exit code 65:
```

In looking at the iOS Scheme, which is what I was building, in the Build section it shows 2 targets: 
LogKit iOS & LogKit iOS Tests.  

The Tests target is currently checked for Analyze, Test, and Run.  I don't think Run should be checked and unchecking it in my copy allowed it to build fine.

I think it should also be unchecked in the OS X one too.  It's not checked in the TV or Watch OS ones.

**Comment by justinpawela** [comment]
Thanks for this. I'm going to check out your PR.

I did test with Carthage pretty heavily whilst figuring out how to manage that Advertising ID compiler flag, but I did so using tvOS. :frowning:  I'm not sure how the iOS / tvOS schemes deviated from each other.

**Comment by justinpawela** [comment]
Interestingly, my Xcode does not show the "Run" product as checked. _However_, when I check `git status` after just poking around in the schemes without changing anything, I can see that Xcode silently updated the OS X and iOS schemes to change the "Run" setting from `YES` to `NO`.

Thanks Xcode! :confused:

I will get this squared away.
