### ISSUE TITLE
compilation error in Xcode 7 beta 6 : print method signature

### ISSUE THREAD

**Issue by jpaas** [logkit/logkit#4]
On Xcode 7, beta 6 the swift-2.0 branch is not compiling...

.../Pods/LogKit/Source/LogKit.swift:250:9: 'print(_:appendNewline:)' is unavailable: Please use 'terminator: ""' instead of 'appendNewline: false': 'print((...), terminator: "")'

**Comment by justinpawela** [comment]
Thanks for reporting! Fixed in Swift 2.0 branch by commit 5d42770056c469290dd0168b3ee7c87af1fa0961
