### ISSUE TITLE
Compilation errors in Xcode 7.0 (7A220)

### ISSUE THREAD

**Issue by Narayane** [logkit/logkit#5]
Hi,

a lot of errors when I try to use LogKit 1.0.4 from Cocoapods.

![logkit](https://cloud.githubusercontent.com/assets/4921308/10104991/c97192e0-63ac-11e5-97cd-5afed9937d27.png)

Regards.

**Comment by justinpawela** [comment]
Thanks for the report!  LogKit 2.0 is coming this week, with support for Swift 2 and Xcode 7.  That will eliminate these errors.

**Comment by justinpawela** [comment]
Closed by 4d86fea8ee3a6c60e27a1426684b1682c54d9ba0.

LogKit 2 will compile with Xcode 7. Thanks for your report!
