### ISSUE TITLE
2.0.0 needs to be pushed to CocoaPods trunk

### ISSUE THREAD

**Issue by jshier** [logkit/logkit#6]
1.1.0 is still the latest version listed in CocoaPods.

**Comment by justinpawela** [comment]
Thanks, still cleaning up a few things first!

**Comment by jshier** [comment]
No problem, just a reminder then I guess.

**Comment by justinpawela** [comment]
Closed by 4d86fea8ee3a6c60e27a1426684b1682c54d9ba0.

Thanks for the reminder!
